config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :recipes, :cuisines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def create
    data = params[:cuisine]

    cuisine = Cuisine.new(name: data[:name])
    cuisine.save!

    redirect_to cuisine_path(cuisine.id)
  end

  def new
    @cuisine = Cuisine.new
  end

  def show
    @cuisine = Cuisine.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @cuisines = Cuisine.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def create # TO-DO: Improve this method.
    data = params[:recipe]

    recipe = Recipe.new(
      title: data[:title],
      recipe_type: data[:recipe_type],
      cuisine_id: data[:cuisine_id],
      difficulty: data[:difficulty],
      cook_time: data[:cook_time],
      ingredients: data[:ingredients],
      method: data[:method]
    )
    recipe.save!

    redirect_to recipe_path(recipe.id)
  end

  def new
    @recipe = Recipe.new
    @cuisines = Cuisine.all
  end

  def show
    @recipe = Recipe.find params[:id]
  end

  # def update
  #   @article = Article.find(params[:id])
  #
  #   if @article.update(article_params)
  #     redirect_to @article
  #   else
  #     render 'edit'
  #   end
  # end
  #
  # def destroy
  #   @article = Article.find(params[:id])
  #   @article.destroy
  #
  #   redirect_to articles_path
  # end
  #
  # private
  #   def article_params
  #     params.require(:article).permit(:title, :text)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/cuisines/new.html.erb
<%= form_for @cuisine do |f| %>
  <p>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %><br>
  </p>
  <p><%= f.submit 'Enviar' %></p>
  <p><%= link_to "Voltar", root_path %></p>

<% end %>

app/views/cuisines/show.html.erb
<h1>Detalhes</h1>
<h3><%= @cuisine.name %></h3>

<%= link_to "Voltar", root_path %>
<br>
<%= link_to "Excluir", cuisine_path(@cuisine),
    method: :delete,
    data: { confirm: 'Are you sure?' } %>

app/views/home/index.html.erb
<h1>CookBook</h1>

<p>Bem-vindo ao maior livro de receitas online</p>
<p>Welcome to the biggest online cookbook</p>

<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe_path(recipe.id) %></h1>
  <li><%= recipe.recipe_type %></li>
  <li><%= recipe.cuisine.name %></li>
  <li><%= recipe.difficulty %></li>
  <li><%= recipe.cook_time %> minutos</li>
<% end %>

<%= link_to 'Enviar uma receita', new_recipe_path %>
<br>
<%= link_to 'Cadastrar uma cozinha', new_cuisine_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<!-- TO-DO: Improve this method: -->
<%= form_for @recipe do |f| %>
  <p>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %><br>
  </p>
  <p>
    <%= f.label :recipe_type, 'Tipo da Receita' %>
    <%= f.text_field :recipe_type %><br>
  </p>
  <p>
    <%= f.label :cuisine_id, 'Cozinha '%>
    <%= f.collection_select(:cuisine_id, @cuisines, :id, :name) %>
  </p>
  <p>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %><br>
  </p>
  <p>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %><br>
  </p>
  <p>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_field :ingredients %><br>
  </p>
  <p>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_field :method %><br>
  </p>
  <p><%= f.submit 'Enviar' %></p>
  <p><%= link_to "Voltar", root_path %></p>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>
  <p><%= @recipe.recipe_type %></p>
  <p><%= @recipe.cuisine.name %></p>
  <p><%= @recipe.difficulty %></p>
  <p><%= @recipe.cook_time %> minutos</p>

<h3>Ingredientes</h3>
  <p><%= @recipe.ingredients %></p>

<h3>Como Preparar</h3>
  <p><%= @recipe.method %></p>

<%= link_to "Voltar", root_path %>
<br>
<%= link_to "Excluir", recipe_path(@recipe),
    method: :delete,
    data: { confirm: 'Are you sure?' } %>